name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
    outputs:
      TAG: ${{ steps.get_tag.outputs.TAG }}
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sed -i 's/0.0.1/${{ needs.prepare.outputs.TAG }}/g' package.json
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run cleanForPublish
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
