name: Node.js Package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          persist-credentials: false
      - run: npm lint
      - run: npm test
      - run: npm run removeDocsAndTests
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
